export const inputControlsArr=[
    {
        name:'que',
        lbl:'Question',
        tag:'textarea',
        val:" ",
        errorMsg:'',
        isShowErrorMsg:false
    },
    {
        name:'opt1',
        lbl:'option1',
        tag:'input',
        type:'text',
        val:'',
        errorMsg:'',
        isShowErrorMsg:false
    },
    {
        name:'opt2',
        lbl:'option2',
        tag:'input',
        type:'text',
        val:'',
        errorMsg:'',
        isShowErrorMsg:false
    },
    {
        name:'opt3',
        lbl:'option3',
        tag:'input',
        type:'text',
        val:'',
        errorMsg:'',
        isShowErrorMsg:false
    },
    {
        name:'opt4',
        lbl:'option4',
        tag:'input',
        type:'text',
        val:'',
        errorMsg:'',
        isShowErrorMsg:false
    },
    {
        name:'type',
        lbl:'Type',
        tag:'input',
        type:'radio',
        options:['Single', 'Multiple'],
        values:['S','M'],
        val:'',
        errorMsg:'',
        isShowErrorMsg:false
    },
    {
        name:'ans',
        lbl:'Answer',
        tag:'select',
        opitons:['A','B','C','D','AB','AC','AD','BC','BD','CD','ABC','ABD','ACD','BCD','ABCD'],
        val:'',
        errorMsg:'',
        isShowErrorMsg:false
    }
]